export const types = {
  LOADING: "LOADING",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  POST_USERS: "POST_USERS",
  CLEAR_USERS_DATA: "CLEAR_USERS_DATA",
  DELETE_USER: "DELETE_USER",
  EDIT_PAGE: "EDIT_PAGE",
  EDIT_USER: "EDIT_USER",
  EDIT_PAGE_FALSE: "EDIT_PAGE_FALSE",
  USER_WAS_EDITED: "USER_WAS_EDITED",
};
